import { addDays, format, subDays, subHours } from "date-fns";
import { DEMO_USER_ID } from "@/lib/constants";
import type { FollowUp, Interaction, Person, Tag } from "@/lib/types";

const tags: Tag[] = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    userId: DEMO_USER_ID,
    name: "Design club",
    createdAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    userId: DEMO_USER_ID,
    name: "Birch Hall",
    createdAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    userId: DEMO_USER_ID,
    name: "Econ 201",
    createdAt: "2026-01-10T10:00:00.000Z",
  },
];

export function createDemoPeople(now = new Date()): Person[] {
  const timestamp = now.toISOString();

  return [
    {
      id: "20000000-0000-4000-8000-000000000001",
      slug: "amelia-chen-4hkq",
      userId: DEMO_USER_ID,
      fullName: "Amelia Chen",
      preferredName: "Amelia",
      profilePhotoUrl: null,
      instagramUsername: "mayamakes",
      phoneNumber: "(415) 555-0142",
      email: "maya@example.edu",
      birthday: format(addDays(now, 3), "yyyy-MM-dd"),
      hometown: "Oakland, California",
      dormOrResidence: "Birch Hall",
      major: "Product design",
      graduationYear: 2027,
      relationshipStrength: 4,
      relationshipLabel: "Studio partner in crime",
      remindersEnabled: true,
      reminderIntervalDays: null,
      status: "active",
      firstMetAt: subDays(now, 184).toISOString(),
      firstMetLocation: "Design club kickoff",
      generalNotes:
        "Building a campus thrift map. Loves ceramics and always orders an oat cortado.",
      createdAt: subDays(now, 184).toISOString(),
      updatedAt: timestamp,
      lastInteractionAt: subDays(now, 19).toISOString(),
      tags: [tags[0], tags[1]],
    },
    {
      id: "20000000-0000-4000-8000-000000000002",
      slug: "luis-ortega-9mtb",
      userId: DEMO_USER_ID,
      fullName: "Luis Ortega",
      preferredName: "Luis",
      profilePhotoUrl: null,
      instagramUsername: "luislistens",
      phoneNumber: "(510) 555-0188",
      email: null,
      birthday: null,
      hometown: "San Diego, California",
      dormOrResidence: "Off campus",
      major: "Economics",
      graduationYear: 2026,
      relationshipStrength: 3,
      relationshipLabel: null,
      remindersEnabled: true,
      reminderIntervalDays: null,
      status: "active",
      firstMetAt: subDays(now, 230).toISOString(),
      firstMetLocation: "Econ 201 study group",
      generalNotes: "Runs the student radio late-night show. Ask about the spring lineup.",
      createdAt: subDays(now, 230).toISOString(),
      updatedAt: timestamp,
      lastInteractionAt: subDays(now, 38).toISOString(),
      tags: [tags[2]],
    },
    {
      id: "20000000-0000-4000-8000-000000000003",
      slug: "amara-okafor-3wqd",
      userId: DEMO_USER_ID,
      fullName: "Amara Okafor",
      preferredName: "Amara",
      profilePhotoUrl: null,
      instagramUsername: "amaraokafor",
      phoneNumber: null,
      email: "amara@example.edu",
      birthday: null,
      hometown: "Portland, Oregon",
      dormOrResidence: "Juniper House",
      major: "Environmental science",
      graduationYear: 2028,
      relationshipStrength: 2,
      relationshipLabel: null,
      remindersEnabled: true,
      reminderIntervalDays: null,
      status: "active",
      firstMetAt: subHours(now, 30).toISOString(),
      firstMetLocation: "Campus garden volunteer day",
      generalNotes: "Researching urban pollinators. Wants to try the dumpling place.",
      createdAt: subHours(now, 30).toISOString(),
      updatedAt: timestamp,
      lastInteractionAt: subHours(now, 30).toISOString(),
      tags: [],
    },
    {
      id: "20000000-0000-4000-8000-000000000004",
      slug: "noah-park-7fkz",
      userId: DEMO_USER_ID,
      fullName: "Noah Park",
      preferredName: "Noah",
      profilePhotoUrl: null,
      instagramUsername: "noahpark",
      phoneNumber: "(650) 555-0101",
      email: "noah@example.edu",
      birthday: format(addDays(now, 11), "yyyy-MM-dd"),
      hometown: "Seattle, Washington",
      dormOrResidence: "Birch Hall",
      major: "Computer science",
      graduationYear: 2027,
      relationshipStrength: 2,
      relationshipLabel: null,
      remindersEnabled: true,
      reminderIntervalDays: 60,
      status: "active",
      firstMetAt: subDays(now, 140).toISOString(),
      firstMetLocation: "Birch Hall lounge",
      generalNotes: "Plays intramural volleyball. Looking for a frontend project.",
      createdAt: subDays(now, 140).toISOString(),
      updatedAt: timestamp,
      lastInteractionAt: subDays(now, 23).toISOString(),
      tags: [tags[1]],
    },
    {
      id: "20000000-0000-4000-8000-000000000005",
      slug: "priya-shah-6dnc",
      userId: DEMO_USER_ID,
      fullName: "Priya Shah",
      preferredName: "Priya",
      profilePhotoUrl: null,
      instagramUsername: "priyareads",
      phoneNumber: "(408) 555-0134",
      email: "priya@example.edu",
      birthday: null,
      hometown: "Fremont, California",
      dormOrResidence: "Cedar Court",
      major: "Comparative literature",
      graduationYear: 2026,
      relationshipStrength: 4,
      relationshipLabel: null,
      remindersEnabled: true,
      reminderIntervalDays: null,
      status: "active",
      firstMetAt: subDays(now, 310).toISOString(),
      firstMetLocation: "First-year seminar",
      generalNotes: "Editing the lit journal. Her sister is visiting later this month.",
      createdAt: subDays(now, 310).toISOString(),
      updatedAt: timestamp,
      lastInteractionAt: subDays(now, 8).toISOString(),
      tags: [],
    },
  ];
}

export function createDemoInteractions(now = new Date()): Interaction[] {
  const people = createDemoPeople(now);

  return [
    {
      id: "30000000-0000-4000-8000-000000000001",
      personId: people[0].id,
      userId: DEMO_USER_ID,
      type: "coffee",
      occurredAt: subDays(now, 19).toISOString(),
      note: "Talked about her thrift-map prototype and summer plans.",
      customLabel: null,
    customIcon: null,
    sourceUpdateId: null,
      createdAt: subDays(now, 19).toISOString(),
      updatedAt: subDays(now, 19).toISOString(),
    },
    {
      id: "30000000-0000-4000-8000-000000000002",
      personId: people[0].id,
      userId: DEMO_USER_ID,
      type: "event",
      occurredAt: subDays(now, 54).toISOString(),
      note: "Design club critique night.",
      customLabel: null,
    customIcon: null,
    sourceUpdateId: null,
      createdAt: subDays(now, 54).toISOString(),
      updatedAt: subDays(now, 54).toISOString(),
    },
    {
      id: "30000000-0000-4000-8000-000000000003",
      personId: people[0].id,
      userId: DEMO_USER_ID,
      type: "met",
      occurredAt: people[0].firstMetAt,
      note: "Met at the design club kickoff.",
      customLabel: null,
    customIcon: null,
    sourceUpdateId: null,
      createdAt: people[0].firstMetAt,
      updatedAt: people[0].firstMetAt,
    },
  ];
}

export function createDemoFollowUps(now = new Date()): FollowUp[] {
  const people = createDemoPeople(now);

  return [
    {
      id: "40000000-0000-4000-8000-000000000001",
      personId: people[4].id,
      userId: DEMO_USER_ID,
      text: "Send the lit journal printer contact",
      dueAt: subDays(now, 1).toISOString(),
      completedAt: null,
      createdAt: subDays(now, 5).toISOString(),
      updatedAt: subDays(now, 5).toISOString(),
      person: people[4],
    },
    {
      id: "40000000-0000-4000-8000-000000000002",
      personId: people[2].id,
      userId: DEMO_USER_ID,
      text: "Share the campus garden group chat",
      dueAt: now.toISOString(),
      completedAt: null,
      createdAt: subDays(now, 1).toISOString(),
      updatedAt: subDays(now, 1).toISOString(),
      person: people[2],
    },
    {
      id: "40000000-0000-4000-8000-000000000003",
      personId: people[1].id,
      userId: DEMO_USER_ID,
      text: "Ask about the spring radio lineup",
      dueAt: addDays(now, 4).toISOString(),
      completedAt: null,
      createdAt: subDays(now, 2).toISOString(),
      updatedAt: subDays(now, 2).toISOString(),
      person: people[1],
    },
    {
      id: "40000000-0000-4000-8000-000000000004",
      personId: people[0].id,
      userId: DEMO_USER_ID,
      text: "Send ceramics studio hours",
      dueAt: subDays(now, 8).toISOString(),
      completedAt: subDays(now, 7).toISOString(),
      createdAt: subDays(now, 12).toISOString(),
      updatedAt: subDays(now, 7).toISOString(),
      person: people[0],
    },
  ];
}
