-- Sharing a person as a siyi.app link instead of a vCard file.
--
-- Additive only. The vCard path is untouched; a link is a second way to hand
-- someone a card. The row here is the whole permission: what it exposes, how
-- long it lives, and whether it has been called back.
--
-- The token is generated by the app from 192 bits of CSPRNG output, never from
-- the person's id or name, so nothing about a link hints at what it points to.

create table if not exists public.person_shares (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  -- A share must not outlive its person. Deleting them deletes their links.
  person_id uuid not null references public.people(id) on delete cascade,
  token text not null check (token ~ '^[A-Za-z0-9_-]{32}$'),
  -- The field picker's answer, exactly as the sharer left it. Anything absent
  -- reads as false, so an older row can only ever expose less.
  fields jsonb not null default '{}'::jsonb,
  -- Null means the sharer deliberately chose a link with no expiry.
  expires_at timestamptz,
  revoked_at timestamptz,
  last_viewed_at timestamptz,
  view_count integer not null default 0 check (view_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Resolving a link is a lookup by token and nothing else, so it has to be both
-- unique and indexed.
create unique index if not exists person_shares_token_idx
  on public.person_shares(token);

-- Listing the live links on one person, which is what the share sheet asks for.
create index if not exists person_shares_person_idx
  on public.person_shares(user_id, person_id, created_at desc);

drop trigger if exists person_shares_set_updated_at on public.person_shares;
create trigger person_shares_set_updated_at
before update on public.person_shares
for each row execute function public.set_updated_at();

alter table public.person_shares enable row level security;

-- Owner-only, all four verbs. Viewers of a link never touch this table
-- directly: the public page reads it through the service role after the token
-- has been validated, so anonymous access is never opened up.

drop policy if exists "Person shares are visible to their owner"
  on public.person_shares;
create policy "Person shares are visible to their owner"
on public.person_shares for select
using (auth.uid() = user_id);

drop policy if exists "Person shares can be created by their owner"
  on public.person_shares;
create policy "Person shares can be created by their owner"
on public.person_shares for insert
with check (
  auth.uid() = user_id and
  exists (
    select 1
    from public.people
    where people.id = person_shares.person_id
      and people.user_id = auth.uid()
  )
);

drop policy if exists "Person shares can be updated by their owner"
  on public.person_shares;
create policy "Person shares can be updated by their owner"
on public.person_shares for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Person shares can be deleted by their owner"
  on public.person_shares;
create policy "Person shares can be deleted by their owner"
on public.person_shares for delete
using (auth.uid() = user_id);
